server:
  port: 8080


spring:
  application:
      name: blog
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml

thymeleaf:
  cache: false
#设置静态资源路径，多个以逗号分隔
spring.resources.static-locations: classpath:static/,file:static/
